site_name: My Docs
nav: 
  - welcome: index.md
  - sdk: sdkconfigration.md
  - coin: coin&address.md
  - Setup-Kubernetes: Setup-Kubernetes.md
  - npm-packages: npm-packages.md
  - explorer-k8s-deployment: explorer-k8s-deployment.md
  - nginx.deployment.k8s: nginx.deployment.k8s.md
  - color-wallet: color-wallet.md
theme: material

